spring:
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins:
        - ${FRONT_END_URL}
cta:
  train-api-key: ${TRAIN_API_KEY}
rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN}
  environment: ${ROLLBAR_ENVIRONMENT}