spring:
  graphql:
    graphiql:
      enabled: false
    schema:
      printer:
        enabled: false
    cors:
      allowed-origins:
        - https://studio.apollographql.com #remove if you are not using Apollo Studio
        - ${FRONT_END_URL}
cta:
  train-api-key: ${TRAIN_API_KEY}
